### PR TITLE
added new claim child benefit service

### PR DESCRIPTION
**Pull request by danielelder**
Could you both cast an eye over the new files I've added for Claim Child Benefit service.

### CODE REVIEW

**Comment by Marat-Faizov** [comment]
@danielelder There are few Claim Child Benefit services, I had brief look, I couldn't find the one with only one WCAG issue

**Comment by danielelder** [comment]
> @danielelder There are few Claim Child Benefit services, I had brief look, I couldn't find the one with only one WCAG issue

Not sure it was just what I was given to create the statement, I've asked Lammy to take a look.

**Comment by Marat-Faizov** [comment]
Perfect, @lammyjjones just confirmed

**Review by Marat-Faizov — APPROVED** [review]
looks good

**Comment by danielelder** [comment]
Closing as commits were unsigned

**Pull request closed without merging**
